[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scancode-service"
version = "0.2.0"
dynamic=["dependencies"]

[project.scripts]
scancode-service = "scancode_extensions.webserver:start"

[tool.setuptools.package-data]
"scancode_extensions.resources" = ["*.yaml"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.in"] }