[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scancode-service"
version = "0.0.1"

[tool.pytest.ini_options]
log_file = "timing.log"
log_file_level = "WARN"