[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scancode-service"
version = "0.1.0"
dependencies = [
    "scancode-toolkit==32.0.8",
    "click==8.1.7",
    "fastapi[all]==0.110.0"
]

[project.scripts]
scancode-service = "scancode_extensions.service:start"

[tool.pytest.ini_options]
log_file = "timing.log"
log_file_level = "WARN"